In [16]:
import numpy as np
import pandas as pd

In [17]:
def one_hot_encode(X):
    choices = list(set(X))
    n = len(choices)

    res = np.zeros((len(X), n))
    
    for i, t in enumerate(X):
        res[i][choices.index(t)] = 1
        
    return res

In [18]:
df = pd.read_csv("features_label2.csv",index_col=False)[["id","count","road","road_type","speed_limit","temp","rain","snow"]]
df

id  count            road road_type  speed_limit  \
0             SAMSON@2019@6      7          SAMSON    BOULEV          0.0   
1           CHOMEDEY@2019@6     11        CHOMEDEY    BOULEV          0.0   
2     MAURICE-GAUVIN@2019@6      2  MAURICE-GAUVIN       RUE         50.0   
3       RENE-LAENNEC@2019@6      3    RENE-LAENNEC      VOIE          0.0   
4      CARTIER OUEST@2019@6     10   CARTIER OUEST       RUE          0.0   
...                     ...    ...             ...       ...          ...   
1732          PIE-IX@2017@1      2          PIE-IX    BOULEV         50.0   
1733      BELLEVILLE@2017@1      2      BELLEVILLE    AVENUE         40.0   
1734      BEAUREGARD@2017@1      2      BEAUREGARD       RUE         40.0   
1735             74E@2017@1      2             74E    AVENUE         40.0   
1736   DE L HARMONIE@2017@1      1   DE L HARMONIE       RUE          0.0   

        temp   rain  snow  
0     18.220  2.693  0.00  
1     18.220  2.693  0.00  
2     18.220  2.693  0.00  
3     18.220  2.693  0.00  
4     18.220  2.693  0.00  
...      ...    ...   ...  
1732  -4.547  1.819  8.42  
1733  -4.547  1.819  8.42  
1734  -4.547  1.819  8.42  
1735  -4.547  1.819  8.42  
1736  -4.547  1.819  8.42  

[1737 rows x 8 columns]

In [19]:
print(one_hot_encode(df["speed_limit"]))

[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 ...
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


In [20]:
new_df = pd.DataFrame(np.c_[one_hot_encode(df["road_type"]), one_hot_encode(df["speed_limit"]), df["temp"], df["rain"], df["snow"],df["count"]])

In [21]:
new_df

0    1    2    3    4    5    6    7    8    9   ...   14   15   16  \
0     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
1     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
2     0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
4     0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1732  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1733  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  1.0   
1734  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   
1735  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  1.0   
1736  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   

       17   18   19      20     21    22    23  
0     0.0  0.0  0.0  18.220  2.693  0.00   7.0  
1     0.0  0.0  0.0  18.220  2.693  0.00  11.0  
2     1.0  0.0  0.0  18.220  2.693  0.00   2.0  
3     0.0  0.0  0.0  18.220  2.693  0.00   3.0  
4     0.0  0.0  0.0  18.220  2.693  0.00  10.0  
...   ...  ...  ...     ...    ...   ...   ...  
1732  1.0  0.0  0.0  -4.547  1.819  8.42   2.0  
1733  0.0  0.0  0.0  -4.547  1.819  8.42   2.0  
1734  0.0  0.0  0.0  -4.547  1.819  8.42   2.0  
1735  0.0  0.0  0.0  -4.547  1.819  8.42   2.0  
1736  0.0  0.0  0.0  -4.547  1.819  8.42   1.0  

[1737 rows x 24 columns]

In [22]:
new_df.to_csv("cleanest_dataset2.csv",index=False)